### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by qaExamDeveloper** [ibraynov/QA-Exam#2]
2.3.2.	Use Case 2 (Navigation bar)

The navigation bar has navigational hyperlinks to the home page, albums list, categories list and the search bar. As well as it should have navigation to the Album creation. 

2.3.2.1.1.	Navigation bar – user management
When the visitor is unregistered, hyperlinks navigating to the Login and Register page should be present. When the visitor is registered or administrator a hyperlink navigating to the Logout page should be present instead. When user is successfully logged out, there should be a redirect to the home page.

**Comment by ibraynov** [comment]
Woks as expected

Test scenarios.
Precondition: User not logged in
1.Open a browser
2. Enter address
3. Page is displayed
4. All navigational hyperlinks are displayed and working

Test scenarios. 
Precondition: User logged in
1.Open a browser
2. Enter address
3. Page is displayed
4. All navigational hyperlinks are displayed and working
