### ISSUE TITLE
Album Comment Page

### ISSUE THREAD

**Issue by qaExamDeveloper** [ibraynov/QA-Exam#5]
2.3.5.	Use Case 5 (Album Comment Page)
Information regarding the album name is shown and a comment text box where user can place a comment for the particular album. We do not support text stylization, so there are no buttons for editing the text. The text cannot be empty. When clicking on “Comment” button, if the data is valid, the comment is placed and a redirect to the respective album is made. If the input data is not valid, a respective error box is shown.

**Comment by ibraynov** [comment]
works as descibed in the use case
