### ISSUE TITLE
Add picture to album

### ISSUE THREAD

**Issue by qaExamDeveloper** [ibraynov/QA-Exam#6]
2.3.6.	Use Case 6 (Add picture to album)
In order to add picture to album, one needs to be the album owner or the site administrator.  By clicking “Add picture” from Album view, the user is navigated to a page and prompted for picture name, picture description and picture url, which must be a valid URL of a picture extension. Clicking on “Create picture” button validates all the fields. If everything is validated, the picture is added and the user is redirected back to the album. Otherwise a message is shown in the error box.

**Comment by ibraynov** [comment]
Picture is added correctly
