### ISSUE TITLE
Categories list

### ISSUE THREAD

**Issue by qaExamDeveloper** [ibraynov/QA-Exam#7]
2.3.7.	Use Case 7 (Categories list)
Clicking on the Categories hyperlink from the header navigates to the categories list. For any normal user, a category name and the number of albums in it is shown. Each category is hyperlink, leading to category view, where all album blocks in that category are shown in descending order by their creation. If the user is administrator, buttons for adding, editing or deleting the category are present.

**Comment by ibraynov** [comment]
works as described
